In [1]:
%run fungsi_save.ipynb

In [2]:
#Read dataset file
data = pd.read_csv('ekstraksi.csv')

In [3]:
#nambah identitas output1
output1 = [] #1 = lymphoid (lymphoblast and lymphocyte), 0 = non-lymphoid, for first stage NN-PSO
output2 = [] #1 = lymphoblast, 0 = non-lymphoblast (lymphocyte), 2 = non-lymphoid, for multiclass classification
output3 = [] #1 = lymphoblast, 0 = non-lymphoblast (lymphocyte), for second stage NN-PSO
X = np.array(data["Citra"]) #original name label
#print(X)
for i in range(len(data)):
    if X[i] == "Limfoblas":
        output1.append(1)
        output2.append(1)
        output3.append(1)
    elif X[i] == "Limfosit":
        output1.append(1)
        output2.append(0)
        output3.append(0)
    elif X[i] == "Limfoma":
        output1.append(1)
        output2.append(0)
        output3.append(0)
    else:
        output1.append(0)
        output2.append(2)
        output3.append(0)
y = output1 #label output1
y2 = output2 #label output2
y3 = output3 #label output3
data = data.drop(['Citra'], axis=1) #delete the name label

In [4]:
#normalisasi
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
len_databaru = np.size(data, axis=1)-1
data.iloc[:,:len_databaru] = scaler.fit_transform(data.iloc[:,:len_databaru])
data

LuasInti  KelilingInti  SolidityInti  GranularityInti  CircularityInti  \
0     0.531275      0.225414      0.929101         0.796842         0.758254   
1     0.184900      0.095028      0.917387         0.765927         0.866082   
2     0.291214      0.120884      0.997386         0.710162         0.978725   
3     0.207731      0.106961      0.971241         0.393771         0.841503   
4     0.664471      0.236022      0.973881         0.854911         0.879461   
5     0.153877      0.080884      0.953759         0.790910         0.877085   
6     0.565075      0.215912      0.986423         0.849561         0.855795   
7     0.157874      0.085304      0.960825         0.880525         0.850949   
8     0.655396      0.247293      0.970284         0.798327         0.809996   
9     0.517243      0.215249      0.856690         0.838349         0.790024   
10    0.164313      0.074917      0.996711         0.828149         0.987615   
11    0.110256      0.064530      0.983638         0.805939         0.838563   
12    0.268184      0.131934      0.971779         0.923594         0.823858   
13    0.298347      0.135249      0.992985         0.804834         0.877769   
14    0.315283      0.171713      0.921275         0.910047         0.682203   
15    0.466834      0.231823      0.935543         0.825374         0.643085   
16    0.283686      0.150497      0.928947         0.834917         0.736812   
17    0.357649      0.149171      0.985535         0.793529         0.915655   
18    0.567514      0.373481      0.915448         0.790046         0.358583   
19    0.573532      0.236022      0.938534         0.846372         0.762886   
20    0.394741      0.182541      0.876008         0.739456         0.771283   
21    0.485828      0.275359      0.868472         0.916828         0.512910   
22    0.354491      0.208177      0.866225         0.744617         0.581056   
23    0.402189      0.162652      0.970660         0.878887         0.913455   
24    0.740168      0.273591      0.962030         0.906739         0.782762   
25    0.602062      0.223867      0.953802         0.853852         0.863453   
26    0.399358      0.189834      0.933749         0.965464         0.739045   
27    0.358567      0.163978      0.943541         0.853369         0.814111   
28    0.561068      0.219890      0.961312         0.782326         0.828077   
29    0.398853      0.164199      0.987312         0.736272         0.895548   
...        ...           ...           ...              ...              ...   
1707  0.443506      0.209724      0.884783         0.681138         0.708825   
1708  0.436642      0.238011      0.875974         0.657148         0.580023   
1709  0.480815      0.339227      0.800598         0.935267         0.358655   
1710  0.391917      0.283315      0.884723         0.794508         0.397185   
1711  0.298713      0.149613      0.925359         0.819846         0.776828   
1712  0.518550      0.348950      0.776658         0.748038         0.368601   
1713  0.319871      0.196243      0.903289         0.711269         0.575241   
1714  0.518909      0.281989      0.831758         0.765219         0.526693   
1715  0.518452      0.335691      0.879862         0.928668         0.394150   
1716  0.569024      0.280442      0.953606         0.659640         0.581636   
1717  0.493080      0.318232      0.811851         0.708955         0.410507   
1718  0.469040      0.236906      0.906118         0.460066         0.625425   
1719  0.446917      0.223204      0.848394         0.587042         0.652436   
1720  0.504448      0.299006      0.779135         0.672765         0.465855   
1721  0.223905      0.138343      0.906297         0.787803         0.666982   
1722  0.383013      0.276022      0.905451         0.603406         0.405359   
1723  0.511606      0.319337      0.918344         0.390751         0.423448   
1724  0.458355      0.217901      0.956280         0.971023         0.692078   
1725  

In [5]:
len(data.shape)

2

In [6]:
#Insert all of the outputs into the dataset
data["output1"] = y
data["output2"] = y2
data["output3"] = y3
X = data
total_features = np.size(X, axis=1)
#print(X)

In [7]:
len_data = np.size(X, axis=1)-1
len_data

31

In [8]:
X = np.array(X)
np.random.shuffle(X)
#X = X.sample(frac = 1) untuk data yang berbentuk dataframe
print(X)

[[0.16317671 0.08375691 0.99507861 ... 1.         0.         0.        ]
 [0.25047458 0.13436464 0.89375427 ... 1.         0.         0.        ]
 [0.31777282 0.30983425 0.70093985 ... 0.         2.         0.        ]
 ...
 [0.28762091 0.1798895  0.81361928 ... 0.         2.         0.        ]
 [0.06978821 0.06033149 0.84767601 ... 0.         2.         0.        ]
 [0.14779405 0.08530387 0.97204375 ... 1.         0.         0.        ]]


In [9]:
train_data = X[:int(len(X)*.80+1)] #Remaining 80% to training set
test_data = test_data = X[int(len(X)*.80+1):] #Splits 20% data to test dataset
np.size(test_data,axis=0)

347

In [10]:
train_data

array([[0.16317671, 0.08375691, 0.99507861, ..., 1.        , 0.        ,
        0.        ],
       [0.25047458, 0.13436464, 0.89375427, ..., 1.        , 0.        ,
        0.        ],
       [0.31777282, 0.30983425, 0.70093985, ..., 0.        , 2.        ,
        0.        ],
       ...,
       [0.11539536, 0.06629834, 0.94612098, ..., 1.        , 0.        ,
        0.        ],
       [0.32624816, 0.16751381, 0.91873718, ..., 0.        , 2.        ,
        0.        ],
       [0.29052467, 0.13480663, 0.98509057, ..., 1.        , 0.        ,
        0.        ]])

In [11]:
np.size(test_data,axis=1)

32

In [13]:
len(train_data)

1390

In [14]:
test_data

array([[0.52993957, 0.27337017, 0.80640807, ..., 0.        , 2.        ,
        0.        ],
       [0.48991125, 0.44044199, 0.61520848, ..., 0.        , 2.        ,
        0.        ],
       [0.1288071 , 0.08044199, 0.89246411, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.28762091, 0.1798895 , 0.81361928, ..., 0.        , 2.        ,
        0.        ],
       [0.06978821, 0.06033149, 0.84767601, ..., 0.        , 2.        ,
        0.        ],
       [0.14779405, 0.08530387, 0.97204375, ..., 1.        , 0.        ,
        0.        ]])

In [15]:
save_data(train_data,test_data)
save_data_test(test_data)

In [16]:
np.size(X,axis=0)

1737

In [17]:
output_train_data = train_data[:,(len_data-2)] #output aja lym
output_train_data = np.int_(output_train_data)
output_train_data2 = train_data[:,len_data-1] #output aja limfo
output_train_data2 = np.int_(output_train_data2)
output_train_data3 = train_data[:,len_data] #output aja limfo
output_train_data3 = np.int_(output_train_data3)

In [20]:
output_test_data = test_data[:,(len_data-2)] #output aja untuk output 1
output_test_data = np.int_(output_test_data)
output_test_data2 = test_data[:,(len_data-1)] #output aja untuk output 2
output_test_data2 = np.int_(output_test_data2)
output_test_data3 = test_data[:,(len_data)] #output aja untuk output 3
output_test_data3 = np.int_(output_test_data3)

In [22]:
print("Number of training samples is", len(train_data))
print("Number of validating samples is same as test data", len(test_data))
print("Number of testing samples is", len(test_data))
print(np.size(train_data,axis=1))

Number of training samples is 1390
Number of validating samples is same as test data 347
Number of testing samples is 347
32


In [23]:

#buat misahin data training dan test


#train_data2 = train_data[:,0:(len_data-1)] #fitur aja tanpa output
#a = [] #index fitur yang gak kepake
#for i in range(len(post)):
 #   if post[i,0] == 0:
  #      a.append(i)
#train_data = np.delete(train_data, a ,axis=1) #data fitur yang udah terseleksi

test_data = test_data[:,0:(len_data-1)] #fitur aja tanpa output dan fiturnya lengkap
#test_data2 = np.delete(test_data, a ,axis=1) #data fitur yang udah terseleksi

#save_data1(train_data)
print("Number of training samples is", len(train_data))
print("Number of testing samples is", len(test_data))
print(np.size(train_data,axis=1))
#print(output_train_data[:])
#print(output_train_data2[:])
#print(output1)
print(train_data[0])
#len(pos)

Number of training samples is 1390
Number of validating samples is 347
Number of testing samples is 347
32
[0.16317671 0.08375691 0.99507861 0.8909676  0.88795322 0.47801846
 0.10533104 0.3427346  0.41960955 0.45488996 0.34816343 0.67433051
 0.1582298  0.06468806 0.8833199  0.66043617 0.54466355 0.3171075
 0.28916418 0.2932835  0.41492715 0.61093959 0.27756577 0.65321758
 0.42676647 0.07005688 0.6973406  0.60882563 0.66537    1.
 0.         0.        ]


In [24]:
output_train_data

array([1, 1, 0, ..., 1, 0, 1])

In [25]:
output_train_data2

array([0, 0, 2, ..., 0, 2, 0])

In [26]:
output_test_data

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [27]:
output_test_data2

array([2, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0,
       0, 0, 1, 1, 0, 0, 0, 2, 2, 2, 1, 1, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 2, 0, 1, 0, 1, 2, 0,
       0, 0, 0, 0, 0, 2, 1, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2,
       0, 2, 0, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 2,
       1, 2, 0, 0, 2, 1, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1, 0, 2, 0, 2,
       0, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 0, 2, 1, 2,
       0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1,
       0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 0, 1, 2, 0, 1, 0, 2, 1, 0, 0, 2, 2,
       2, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2, 2, 0, 0, 2, 1, 2, 2, 2, 1,
       0, 2, 2, 1, 1, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2,
       0, 2, 1, 1, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2,
       0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 1, 2, 2, 2, 2,

In [ ]:
#data training NN1
#data training NN2
#data testing NN 2 step
#data training NN biner limfoblas 1 step